### ISSUE TITLE
terraform gitaction이 CI로 구분돼있는데 apply를 하는거면 CD가 맞지 않을까요?

### ISSUE THREAD

**Issue by HumanIearning** [GSM-MSG/SMS-DevOps#27]
https://github.com/GSM-MSG/SMS-DevOps/blob/216b4c06f3350dbe1e53ab0087a9678d1f48b702/.github/workflows/terraform.yml#L62-L70

**Comment by HumanIearning** [comment]
apply는 분기를 해뒀었네요. 근데 gitaction 실행 조건이랑 apply실행 조건이랑 완전히 동일한데 일부러 작성 시 이후에 terraform refactoring할걸 고려해 gitaction 조건에 브랜치만 따로 추가하는 식으로 하려고 한건가요?

https://github.com/GSM-MSG/SMS-DevOps/blob/216b4c06f3350dbe1e53ab0087a9678d1f48b702/.github/workflows/terraform.yml#L3-L7

https://github.com/GSM-MSG/SMS-DevOps/blob/216b4c06f3350dbe1e53ab0087a9678d1f48b702/.github/workflows/terraform.yml#L53-L54

**Comment by NohGaSeong** [comment]
> terraform gitaction이 CI로 구분돼있는데 apply를 하는거면 CD가 맞지 않을까요? 
- apply를 돌리긴하지만 결국 공통된 init 파일을 사용한다점에 포커스를 두고 짜둔 워크플로우라서 CI 라고 명명하였습니다.<br>

> terraform refactoring할걸 고려해 gitaction 조건에 브랜치만 따로 추가하는 식으로 하려고 한건가요?
- 말씀하신대로 저 workflow를 작성할 당시, terraform 코드를 리펙토링 해야겠다라고 생각했고, 추후 리펙토링하게 된다면 리펙토링 작업이 진행되는 브랜치를 조건으로 걸어 plan 을 테스트하고, apply 를 진행하는 작업을 하려고하였습니다.

좋은 이슈 감사드리며 테라폼 코드들을 리펙토링 하기 전에 여러가지 사항들을 모두 고려해서 workflow 파일들을 조금 손 봐야할 듯 싶습니다.
